version: '3.6'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - transcendence

  pgadmin:
    #USED ONLY FOR DEV, DO NOT USE IN PROD
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: your-email@example.com
      PGADMIN_DEFAULT_PASSWORD: your-password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - ./config/pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - transcendence

#  front:
#    build: docker/front
#    volumes:
#      - ./front:/app:delegated
#    ports:
#      - "3000:3000"

networks:
  transcendence:
    driver: bridge
