version: '3.6'

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../backend/image:/backend/image
      - ./ssl:/ssl/
      - ../front/build:/var/www/front
    depends_on:
      - backend
    networks:
      - transcendence

  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: transcendence
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - transcendence

  pgadmin:
    #USED ONLY FOR DEV, DO NOT USE IN PROD
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: your-email@example.com
      PGADMIN_DEFAULT_PASSWORD: your-password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - ./config/pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - transcendence

  frontend:
    container_name: frontend
    build: ./front
    volumes:
      - ../front:/app:delegated
    ports:
      - "3001:3001"
    depends_on:
      - backend
    networks:
      - transcendence

  backend:
    container_name: backend
    build: ./back
    volumes:
      - ../backend:/app:delegated
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - transcendence
    restart: on-failure:5

networks:
  transcendence:
    driver: bridge
