openapi: 3.0.3
info:
  version: 1.0.0
  title: Transcendence - API
  description: >-
    This is a description of API
servers:
  - url: http://localhost:3000/api
tags:
  - name: login
    description: Everything about login
  - name: store
    description: Access to Petstore orders
  - name: user
    description: Operations about user
paths:
  /user:
    post:
      summary: chalenge login
      tags:
        - login
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'
        '401':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'

          
components:
  schemas:
    user:
      type: object
      properties:
        id:
          description: identifiant
          type: integer

